# Copyright 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: skaffold/v4beta14
kind: Config
metadata:
  name: local-stack
requires:
- path: local/event-bus/skaffold.yaml
  configs:
  - event-bus
- path: local/agent-gateway/skaffold.yaml
  configs:
  - agent-gateway
- path: local/dashboard/skaffold.yaml
  configs:
  - dashboard
- path: local/inference-mock/skaffold.yaml
  configs:
  - inference
