# Copyright 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: skaffold/v4beta14
kind: Config
metadata:
  name: inference
build:
  tagPolicy:
    inputDigest: {}
  local:
    concurrency: 0
    push: false
    useDockerCLI: true
    useBuildkit: true
  artifacts:
  - image: dsx-exchange/dsx-inference
    context: .
    docker:
      dockerfile: Dockerfile
      cliFlags:
      - --provenance=false
profiles:
- name: inference-build-mirror
  activation:
  - env: SKAFFOLD_BUILD_MIRROR_REGISTRY=.+
  patches:
  - op: add
    path: /build/artifacts/0/docker/buildArgs
    value:
      BUILDER_IMG: '{{.SKAFFOLD_BUILD_MIRROR_REGISTRY}}/docker.io/library/golang'
      FINAL_IMG: '{{.SKAFFOLD_BUILD_MIRROR_REGISTRY}}/gcr.io/distroless/static-debian12'
deploy:
  statusCheck: true
  statusCheckDeadlineSeconds: 300
  tolerateFailuresUntilDeadline: true
  helm:
    flags:
      install:
      - --timeout=5m
      upgrade:
      - --timeout=5m
    releases:
    - name: dsx-inference
      chartPath: ./deploy
      namespace: csc-event-bus
      createNamespace: false
      skipBuildDependencies: true
      setValueTemplates:
        image.repository: '{{.IMAGE_REPO_dsx_exchange_dsx_inference}}'
        image.tag: '{{.IMAGE_TAG_dsx_exchange_dsx_inference}}'
      setValues:
        image.pullPolicy: IfNotPresent
